### ISSUE TITLE
能不能增加一个登录功能，有的需要vip才能下载不然的话只能下载到预览的部分

### ISSUE THREAD

**Issue by ctftoweb** [weiwei-cool/FanQieNovelDownloadOnWeb#24]
能不能增加一个登录功能，有的需要vip才能下载不然的话只能下载到预览的部分

**Comment by stelahaveno** [comment]
很抱歉，这个功能我们暂时做不到，我们使用手机API进行获取数据，如果您有这方面的需求，您可以去689491527(QQ群)这个地方看看，他们的项目拥有您所提到的这个功能，您的需求可能会在那里得到解决。
