### ISSUE TITLE
把路径改为自定义？

### ISSUE THREAD

**Issue by zhangyouxin123** [weiwei-cool/FanQieNovelDownloadOnWeb#3]
把路径改为自定义？

**Comment by zhangyouxin123** [comment]
临时缓存域名改为自定义域名？

**Comment by stelahaveno** [comment]
抱歉，此版本为内部暂测试版，您提到的功能将在1周内上线，感谢您对开源社区的贡献！

**Comment by stelahaveno** [comment]
您的提议已经实现，感谢您宝贵的建议和您对开源社区的贡献！

**Comment by stelahaveno** [comment]
> 把路径改为自定义？

很抱歉，本人因为“眼疾”(开玩笑，并非生理疾病)，未能看到此要求，故重新开启此issue，很抱歉给您带来不便。

**Comment by stelahaveno** [comment]
已在最新版本添加您提到的

> 把路径改为自定义？

和

> 临时缓存域名改为自定义域名？

两项功能
