### ISSUE TITLE
点击下载出现404

### ISSUE THREAD

**Issue by zhangyouxin123** [weiwei-cool/FanQieNovelDownloadOnWeb#4]
![Uploading QQ截图20231110150209.png…]()

**Comment by zhangyouxin123** [comment]
[
![2023](https://github.com/weiwei-cool/FanQieNovelDownloadOnWeb/assets/35016819/79fb3319-1d62-4340-942f-7685b197b4d3)
](url)

**Comment by stelahaveno** [comment]
您好，很抱歉，由于我未能在文档中清晰的表达使用方法造成了误解，首先，您需要在环境变量中设置`CUSTOM_PATH`以定义您小说的保存路径，此时您可在环境变量定义的路径下找到下载完成的小说。如果您(或其他人)要使用这个功能(下载按钮)，您还需要配合一个webdav服务器，这里推荐[alist](https://github.com/alist-org/alist)，但如果您只是下载小说的话，我不建议您这样做(使用webdav模式)，您可以直接在您设置的位置找到文件，但如果您有这方面的需求，您可以参见[此处](https://github.com/weiwei-cool/FanQieNovelDownloadOnWeb#webdav%E6%A8%A1%E5%BC%8F)以设置这个下载按钮的功能。最后，如果您没有web访问的需求，我推荐您使用本项目的[源项目](https://github.com/xing-yv/fanqie-novel-download)。
