### ISSUE TITLE
[feature] 允许配置默认文件格式

### ISSUE THREAD

**Issue by SerinaNya** [weiwei-cool/FanQieNovelDownloadOnWeb#5]
希望允许通过环境变量等方式配置默认的文件格式。

目前默认格式为 EPUB，只能通过网页上手动更改为 TXT。且每次下载时均需进行此更改操作，带来不便。

**Comment by stelahaveno** [comment]
感谢您的建议，由于我本人使用epub模式，所以其默认为epub，我将在下一个版本实现此功能，敬请期待，谢谢您的建议！
